-- =============================================================================
-- Seed: full 50-agent catalog (47 config-driven agents; the other 3 were
-- seeded by earlier migrations). Code lives in src/agents/catalog/*.
-- =============================================================================

insert into public.agents (slug, name, description, department, tier_required, credits_cost, model)
values
  ('respuesta-leads-entrantes', 'Respondedor de leads entrantes', 'Contesta consultas de leads en minutos con propuesta de siguiente paso.', 'ventas', 'starter', 1, 'sonnet-4.6'),
  ('seguimiento-presupuestos', 'Redactor de seguimiento de presupuestos', 'Reaviva presupuestos enviados que se quedaron sin respuesta.', 'ventas', 'starter', 1, 'sonnet-4.6'),
  ('guion-llamada-comercial', 'Generador de guiones de llamada', 'Guiones de llamada a puerta fría adaptados a tu sector.', 'ventas', 'starter', 1, 'sonnet-4.6'),
  ('manejo-objeciones', 'Entrenador de objeciones de venta', 'Respuestas preparadas para las objeciones que te frenan ventas.', 'ventas', 'starter', 1, 'sonnet-4.6'),
  ('email-reactivacion-clientes', 'Reactivador de clientes dormidos', 'Emails para recuperar clientes que dejaron de comprar.', 'ventas', 'starter', 1, 'sonnet-4.6'),
  ('propuesta-comercial', 'Redactor de propuestas comerciales', 'Convierte un briefing en una propuesta estructurada y persuasiva.', 'ventas', 'scale', 4, 'opus-4.7'),
  ('resumen-llamada-comercial', 'Resumidor de llamadas comerciales', 'Pega la transcripción y recibe resumen, dolores del cliente y próximos pasos.', 'ventas', 'business', 3, 'sonnet-4.6'),
  ('mensaje-linkedin', 'Redactor de mensajes de LinkedIn', 'Solicitudes de contacto y seguimientos que no parecen spam.', 'ventas', 'business', 1, 'sonnet-4.6'),
  ('calificador-leads', 'Calificador de leads', 'Evalúa un lead, puntúa su encaje y te dice qué preguntar.', 'ventas', 'scale', 3, 'opus-4.7'),
  ('respuesta-negociacion', 'Asistente de negociación de precios', 'Qué responder cuando el cliente pide descuento.', 'ventas', 'business', 2, 'sonnet-4.6'),
  ('newsletter-redactor', 'Redactor de newsletters', 'Tu newsletter mensual redactada a partir de tus novedades.', 'marketing', 'starter', 1, 'sonnet-4.6'),
  ('descripcion-producto', 'Redactor de fichas de producto', 'Descripciones de producto que venden, para tienda online o catálogo.', 'marketing', 'starter', 1, 'sonnet-4.6'),
  ('respuesta-comentarios-rrss', 'Respondedor de comentarios en redes', 'Respuestas con criterio a comentarios buenos, malos y trolls.', 'marketing', 'starter', 1, 'sonnet-4.6'),
  ('whatsapp-marketing', 'Redactor de campañas de WhatsApp', 'Mensajes de difusión que no acaban en bloqueo.', 'marketing', 'starter', 1, 'sonnet-4.6'),
  ('calendario-editorial', 'Planificador de calendario editorial', 'Un mes de ideas de contenido adaptadas a tu negocio.', 'marketing', 'business', 2, 'sonnet-4.6'),
  ('anuncio-google-ads', 'Generador de anuncios de Google Ads', 'Titulares y descripciones que cumplen los límites de caracteres.', 'marketing', 'business', 2, 'sonnet-4.6'),
  ('post-blog-seo', 'Redactor de artículos de blog SEO', 'Esquema, introducción y SEO on-page para posicionar un artículo.', 'marketing', 'scale', 4, 'opus-4.7'),
  ('nota-de-prensa', 'Redactor de notas de prensa', 'Notas de prensa con estructura profesional para medios locales.', 'marketing', 'business', 2, 'sonnet-4.6'),
  ('respuesta-quejas-email', 'Respondedor de quejas por email', 'Convierte una queja en una respuesta que conserva al cliente.', 'atencion_cliente', 'starter', 1, 'sonnet-4.6'),
  ('plantillas-faq', 'Generador de respuestas FAQ', 'Respuestas claras y reutilizables para tus preguntas frecuentes.', 'atencion_cliente', 'starter', 1, 'sonnet-4.6'),
  ('respuesta-whatsapp-clientes', 'Respondedor de WhatsApp de clientes', 'Respuestas rápidas y bien escritas para el WhatsApp del negocio.', 'atencion_cliente', 'starter', 1, 'sonnet-4.6'),
  ('mensaje-disculpa-incidencia', 'Comunicador de incidencias', 'Avisa de un retraso o un fallo sin perder la confianza del cliente.', 'atencion_cliente', 'business', 1, 'sonnet-4.6'),
  ('resumen-conversacion-soporte', 'Resumidor de conversaciones de soporte', 'Convierte un hilo largo en estado, acuerdos y siguiente acción.', 'atencion_cliente', 'business', 2, 'sonnet-4.6'),
  ('encuesta-satisfaccion', 'Generador de encuestas de satisfacción', 'Encuestas cortas que la gente sí contesta.', 'atencion_cliente', 'business', 2, 'sonnet-4.6'),
  ('comunicado-cambio-servicio', 'Comunicador de cambios de servicio', 'Anuncia subidas de precio o cambios de condiciones sin fugas de clientes.', 'atencion_cliente', 'business', 2, 'sonnet-4.6'),
  ('acta-reunion', 'Redactor de actas de reunión', 'De tus notas sueltas a un acta con acuerdos y responsables.', 'operaciones', 'starter', 2, 'sonnet-4.6'),
  ('checklist-operativa', 'Generador de checklists operativas', 'Convierte cualquier proceso en una lista de verificación a prueba de olvidos.', 'operaciones', 'starter', 1, 'sonnet-4.6'),
  ('resumen-documento', 'Resumidor de documentos', 'Resume contratos, informes o normativas en lo que te afecta.', 'operaciones', 'starter', 2, 'sonnet-4.6'),
  ('procedimiento-sop', 'Redactor de procedimientos (SOP)', 'Documenta cómo se hacen las cosas para no depender de nadie.', 'operaciones', 'business', 2, 'sonnet-4.6'),
  ('email-proveedores', 'Redactor de emails a proveedores', 'Pedidos, reclamaciones y negociaciones con proveedores, bien escritas.', 'operaciones', 'business', 1, 'sonnet-4.6'),
  ('parte-incidencia-interna', 'Redactor de partes de incidencia', 'Documenta incidencias internas con hechos, causa e impacto.', 'operaciones', 'business', 1, 'sonnet-4.6'),
  ('planificador-tareas-semana', 'Priorizador semanal de tareas', 'Convierte tu lista infinita en un plan de semana realista.', 'operaciones', 'business', 2, 'sonnet-4.6'),
  ('oferta-empleo', 'Redactor de ofertas de empleo', 'Ofertas que atraen al candidato adecuado y ahuyentan al que no encaja.', 'rrhh', 'starter', 1, 'sonnet-4.6'),
  ('comunicado-interno', 'Redactor de comunicados internos', 'Comunica cambios al equipo con claridad y sin malentendidos.', 'rrhh', 'starter', 1, 'sonnet-4.6'),
  ('descripcion-puesto', 'Redactor de descripciones de puesto', 'Define funciones y responsabilidades negro sobre blanco.', 'rrhh', 'business', 1, 'sonnet-4.6'),
  ('preguntas-entrevista', 'Generador de preguntas de entrevista', 'Preguntas que revelan cómo trabaja de verdad el candidato.', 'rrhh', 'business', 2, 'sonnet-4.6'),
  ('plan-onboarding', 'Planificador de onboarding', 'Los primeros 30 días de un empleado nuevo, planificados.', 'rrhh', 'business', 2, 'sonnet-4.6'),
  ('evaluacion-desempeno', 'Preparador de evaluaciones de desempeño', 'Estructura una conversación de feedback justa y sin dramas.', 'rrhh', 'business', 2, 'sonnet-4.6'),
  ('calculador-finiquito', 'Calculador orientativo de finiquitos', 'Desglose orientativo de finiquito con fórmulas visibles, para validar con tu gestoría.', 'rrhh', 'business', 2, 'sonnet-4.6'),
  ('criba-cv', 'Analizador de CVs', 'Evalúa un CV frente a tu puesto y prepara la criba con criterio.', 'rrhh', 'scale', 3, 'opus-4.7'),
  ('reclamacion-impagos', 'Reclamador de facturas impagadas', 'Secuencia de reclamación que cobra sin quemar al cliente.', 'finanzas', 'starter', 1, 'sonnet-4.6'),
  ('conciliador-gastos', 'Conciliador de tickets de gastos', 'Pega tus tickets y gastos y recíbelos categorizados y cuadrados.', 'finanzas', 'business', 2, 'sonnet-4.6'),
  ('resumen-financiero', 'Explicador de resultados', 'Tus números del mes explicados en cristiano, con señales de alerta.', 'finanzas', 'business', 2, 'sonnet-4.6'),
  ('presupuesto-cliente', 'Redactor de presupuestos', 'Presupuestos con partidas claras y condiciones que evitan disgustos.', 'finanzas', 'business', 2, 'sonnet-4.6'),
  ('email-banco-gestoria', 'Comunicador con banco y gestoría', 'Solicitudes formales bien planteadas para que respondan a la primera.', 'finanzas', 'business', 1, 'sonnet-4.6'),
  ('politica-gastos', 'Redactor de políticas de gastos', 'Reglas de gastos claras para que el equipo no tenga que preguntar.', 'finanzas', 'business', 2, 'sonnet-4.6'),
  ('analisis-flujo-caja', 'Analista de flujo de caja', 'Proyecta tu caja de las próximas semanas y avisa de los baches.', 'finanzas', 'scale', 4, 'opus-4.7')
on conflict (slug) do nothing;
